apiVersion: apps/v1
kind: Deployment
metadata:
  name: information
  labels:
    app: information
spec:
  replicas: 1
  selector:
    matchLabels:
      app: information
  template:
    metadata:
      labels:
        app: information
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: information
          image: 496278789073.dkr.ecr.ap-northeast-1.amazonaws.com/skccuser02-information:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/myOrders'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/myOrders'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
